# Base image
FROM alpine:latest

# Install required tools
RUN apk add --no-cache bash docker-cli

# Copy .env to image migrate
COPY .env .

# Set the working directory
WORKDIR /app



# Run down 1
# docker-compose run migrate migrate -path /app/migrations -database "postgres://DB_USER:DB_PASSWORD@db_kyc:5432/DB_NAME?sslmode=disable" down 1
# Run down todas
# docker-compose run migrate migrate -path /app/migrations -database "postgres://DB_USER:DB_PASSWORD@db_kyc:5432/DB_NAME?sslmode=disable" down
# Run Up
# docker-compose run migrate -path /app/migrations -database "postgres://$${DB_USER}:$${DB_PASSWORD}@db_kyc:5432/$${DB_NAME}?sslmode=disable" up
# Run command to check the version of migration
# docker-compose run migrate -path /app/migrations -database "postgres://caciano4:123caciano@db_kyc:5432/trullio?sslmode=disable" version