# Base image
FROM alpine:3.18

# Install required tools
RUN apk add --no-cache bash curl tar

# Install golang-migrate CLI
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xz && \
    mv migrate /usr/local/bin/migrate

# Set the working directory
WORKDIR /app

# Default command to show usage
ENTRYPOINT ["/usr/local/bin/migrate"]