# Base image
FROM golang:1.23-alpine

# Install dependencies
RUN apk add --no-cache git

# Install Air
RUN go install github.com/air-verse/air@latest

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Create tmp directory with appropriate permissions
RUN mkdir -p /app/tmp && chmod -R 777 /app/tmp

# Install Go dependencies
RUN go mod tidy

# Expose development port
EXPOSE 8080

# Run Air
CMD ["air", "-c", ".air.toml"]
